// Code generated by "stringer -type=Color"; DO NOT EDIT.

package main

import "strconv"

const _Color_name = "redblueyellowpinkwhite"

var _Color_index = [...]uint8{0, 3, 7, 13, 17, 22}

func (i Color) String() string {
	i -= 1
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
